name: Run test suite
on: push

jobs:
  build docker:
    name: build
      runs-on: ubuntu-latest
      steps:
        sudo docker build -t synobuild .
  run-tests:
    name: Run
    runs-on: ubuntu-latest
    
    container:
      image: synobuild
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Running composer install
        run: composer install
      - name: Running phpunit
        run: ./vendor/bin/phpunit te
