name: Compile site assets
on: push

jobs:
  compile:
    name: Compile assets
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name : Buil Docker
      - run : docker build -t synobuild .
      - name: Run Docker container to compile assets
        uses: addnab/docker-run-action@v3
        with:
          image: synobuild
          options: -v ${{ github.workspace }}/artifacts:/result_spk  --rm --privileged --env PACKAGE_ARCH=<arch> --env DSM_VER=<dsm-ver>
          run: echo
  
