name: Create
on: push

jobs:
  compile:
    name: Compile assets
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run Docker container to compile assets
        uses: addnab/docker-run-action@v3
        with:
          image:s ynobuild
          options: --rm --privileged --env PACKAGE_ARCH=<arch> --env DSM_VER=<dsm-ver> -v $(pwd)/artifacts:/result_spk
          run:
      - name: Verify assets
        run: ls -l dist
